### ISSUE TITLE
Handle XING headers with 0 num_frames

### ISSUE THREAD

**Issue by droopanu** [thebigmunch/audio-metadata#11]
I'm getting the following error while trying to upload a folder:

[2019-10-14 12:13:36] Logging in to Music Manager
[2019-10-14 12:13:37] Logging in to Mobile Client
[2019-10-14 12:13:38] Loading local songs
[2019-10-14 12:13:39] Comparing hashes
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/usr/local/lib/python3.7/dist-packages/google_music_scripts/commands.py", line 364, in do_upload
    if generate_client_id(song) not in google_client_ids:
  File "/usr/local/lib/python3.7/dist-packages/google_music_proto/musicmanager/utils.py", line 21, in generate_client_id
    song = audio_metadata.load(song)
  File "/usr/local/lib/python3.7/dist-packages/audio_metadata/api.py", line 119, in load
    return parser_cls.load(fileobj)
  File "/usr/local/lib/python3.7/dist-packages/audio_metadata/formats/mp3.py", line 536, in load
    self.streaminfo = MP3StreamInfo.load(self._obj)
  File "/usr/local/lib/python3.7/dist-packages/audio_metadata/formats/mp3.py", line 492, in load
    bitrate = ((audio_size - frames[0]._size) * 8 * frames[0].sample_rate) / num_samples
ZeroDivisionError: division by zero

Most probably one of the mp3 files is broken, but there is no way to figure out which one. 

Would it be possible to add a debugging option to show the file that is being processed so that way I can see what mp3 is broken :)

Cheers,
Liviu

**Comment by thebigmunch** [comment]
So, FYI, this file seems to have an invalid XING header that says there's 0 MPEG frames/data in the file, which is obviously not true. This file shouldn't even have a XING header as it is CBR and not encoded with LAME. This in turn screws up the bitrate calculation by giving audio-metadata an incorrect number of samples.

Probably should raise an exception on this somewhere so it fails predictably and gracefully with a useful message.

**Comment by thebigmunch** [comment]
PS This particular file is actually over Google Music's file size limit of 300 MiB as well, so it couldn't be uploaded anyway : P

**Comment by droopanu** [comment]
did not know there is a 300MB limit.
Well ... good to know :)

**Comment by droopanu** [comment]
BTW, thank you very much for your quick reply :D

I can see 2 feature requests coming from this:
1. Would be good if the uploader would indeed raise an exception for the
divide by 0 failure, print the file name and skip it.
2. Display an error when the file is too big and can't be uploaded,
including the filename, and skip to the next file.

**Comment by thebigmunch** [comment]
For the latter, you can increase the verbosity to see the progress messages that will tell you that the large file wasn't uploaded because of the limit. Either way, it won't be uploaded and move right along.

**Comment by thebigmunch** [comment]
I've added handling of MP3 with XING headers with 0 num_frames. audio-metadata will now load these files, including the one in this issue.

For the specific file in this issue, it technically is a loadable MP3 but seems like its incorrect. The only MPEG frame that isn't a CBR of 128Kbps is the XING frame at 64Kbps. A CBR MP3 using XING is supposed to use the ``Info`` identifier rather than ``Xing``, this file did not. This actually confuses a number of programs to its actual stream info due to their implementations/guesswork.

mutagen assumes VBR due to the XING header not using the ``Info`` string and having the quality indicator field set. Since the XING header doesn't have the number of frames set, mutagen just takes the bitrate from the XING frame, which is the only one that is not 128Kbps and set the duration (length) to 0 seconds.

```
>>> import mutagen
>>> m = mutagen.File('ractive_music_without_subtitles_2019-09-07.mp3')
>>> vars(m.info)
{
    'bitrate': 64000,
    'bitrate_mode': <BitrateMode.VBR: 2>,
    'channels': 2,
    'encoder_settings': '',
    'frame_offset': 303,
    'layer': 3,
    'length': 0.0,
    'mode': 0,
    'padding': False,
    'protected': False,
    'sample_rate': 44100,
    'sketchy': False,
    'version': 1,
}
```

foobar2000 figures out that the file **should** be CBR (though I'm not sure how), but it also just grabs the bitrate from the XING frame. It then uses the bitrate to calculate the duration. Since the bitrate of the XING frame is half the bitrate of every other frame, it detects the duration as double of what it actually is.

audio-metadata now sets the bitrate mode to ``UNKNOWN`` as well as calculating the correct bitrate and duration for this file at the expense of having to count all the MPEG frames in the file. This operation took 10-12 seconds on this 300 MiB file with over 750,000 frames on my desktop. But, now it at least correctly loads it unlike mutagen. And MP3 files of a more average size obviously take much less time.
