### ISSUE TITLE
PyPI tarball differs from GitHub source

### ISSUE THREAD

**Issue by dotlambda** [thebigmunch/audio-metadata#2]
For example, there is a line `bidict>=0.17,<0.18` in the PyPI tarball for version 0.4.0 whereas on GitHub, we have
https://github.com/thebigmunch/audio-metadata/blob/b1f7c6a57d79c341311cb909f83b6ff3bc089f28/setup.py#L32
Why is that?

**Comment by thebigmunch** [comment]
The packaging and dependency management is actually done with poetry. The setup.py is only a shim while waiting for certain tools and services to properly support PEPs 517 and 518, so I was a little lazy with the constraints. Right now, I think all that's left is an issue with Read The Docs. All the actual constraints are defined in the ``tool.poetry.dependencies`` section of ``pyproject.toml``. pip >= 19 should use poetry rather than setuptools to install by default.

PS I wholeheartedly agree with your status message : P

**Comment by dotlambda** [comment]
However, I don't find an upper bound for bidict in https://github.com/thebigmunch/audio-metadata/blob/master/pyproject.toml.

**Comment by thebigmunch** [comment]
That's because I've changed it since last release. Previously, I had it set to ``^0.17`` which means SemVer-compatible. For 0-versioned packages, this would just be ``0.17.x`. I felt that was too constricting (and a hassle). I especially want people to get the C extension the bitstruct author is writing without having to change the constraint. That module makes it easier for people to understand and for me to come back to after some time not using bitwise operations, but using it does slow down loading to be just a bit slower than mutagen where audio-metadata was faster before.

**Comment by dotlambda** [comment]
Alright, thank you! Looking forward to the next release with a relaxed constraint.

**Comment by thebigmunch** [comment]
Thanks. Glad someone's taking notice of this library at all : )

**Comment by dotlambda** [comment]
Honestly, I'm just about google-music-scripts for me :)
